export const FETCH_ALL_HASHTAGS_REQUEST = 'FETCH_ALL_HASHTAG_REQUEST';
export const FETCH_ALL_HASHTAGS_SUCCESS = 'FETCH_ALL_HASHTAGS_SUCCESS';
export const FETCH_ALL_HASHTAGS_ERROR = 'FETCH_ALL_HASHTAGS_ERROR';

// POST HASHTAG

export const FETCH_POST_HASHTAGS_REQUEST = 'FETCH_POST_HASHTAGS_REQUEST';
export const FETCH_POST_HASHTAGS_SUCCESS = 'FETCH_POST_HASHTAGS_SUCCESS';
export const FETCH_POST_HASHTAGS_ERROR = 'FETCH_POST_HASHTAGS_ERROR';