// POSTS
export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';

// POST CONTENT
export const FETCH_CONTENT_REQUEST = 'FETCH_CONTENT_REQUEST';
export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS';
export const FETCH_CONTENT_ERROR = 'FETCH_CONTENT_ERROR';

// WRITE POST
export const PUSH_POST_REQUEST = 'PUSH_POST_REQUEST';
export const PUSH_POST_SUCCESS = 'PUSH_POST_SUCCESS';
export const PUSH_POST_ERROR = 'PUSH_POST_ERROR';
