// POSTS
export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const FETCH_MORE_POST_SUCCESS = 'FETCH_MORE_POST_SUCCESS';
export const FETCH_LIKE_HISTORY_SUCCESS = 'FETCH_LIKE_HISTORY_SUCCESS';
// POST CONTENT
export const FETCH_CONTENT_REQUEST = 'FETCH_CONTENT_REQUEST';
export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS';
export const FETCH_CONTENT_ERROR = 'FETCH_CONTENT_ERROR';

// POST COMMENT
export const FETCH_COMMENT_REQUEST = 'FETCH_COMMENT_REQUEST';
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const FETCH_COMMENT_ERROR = 'FETCH_COMMENT_ERROR';

// POST LIKE
export const FETCH_LIKE_REQUEST = 'FETCH_LIKE_REQUEST';
export const FETCH_LIKE_SUCCESS = 'FETCH_LIKE_SUCCESS';
export const FETCH_LIKE_ERROR = 'FETCH_LIKE_ERROR';

export const SUBMIT_QUERY = 'SUBMIT_QUERY';