export const FETCH_RANK_BY_USERID_SUCCESS = 'FETCH_RANK_BY_USERID_SUCCESS';
export const FETCH_RANK_BY_USERID_ERROR = 'FETCH_RANK_BY_USERID_ERROR';
export const FETCH_RANK_BY_USERID_REQUEST = 'FETCH_RANK_BY_USERID_REQUEST';

export const FETCH_POST_BY_USERID_SUCCESS = 'FETCH_POST_BY_USERID_SUCCESS';
export const FETCH_POST_BY_USERID_ERROR = 'FETCH_POST_BY_USERID_ERROR';
export const FETCH_POST_BY_USERID_REQUEST = 'FETCH_POST_BY_USERID_REQUEST';