export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';